name: ViewerSMP
version: '1.0'
main: com.shingaspt.viewerSMP.ViewerSMP
api-version: '1.21'
load: STARTUP
authors: [ ShingasPT ]
description: ViewerSMP Main Bot
softdepend: [ DiscordSRV, Luckperms, Vault ]